name: Default test job

on:
  workflow_dispatch:
    inputs:
      suite_name:
        description: 'Test suite to execute.'
        required: true
        type: choice
        default: 'default-suite.xml'
        options:
          - 'default-suite.xml'
      contracts:
        description: 'Include contract testing if set to true.'
        required: true
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t api-tests-automation .

      - name: Run Tests in Docker Container
        run: docker run --rm -e SUITE="${{ github.event.inputs.suite_name }}" -e CONTRACTS="${{ github.event.inputs.contracts }}" api-tests-automation